### PR TITLE
Fixing ld_library_path issue.

### PR DESCRIPTION
**Pull request by kwhat**
Also documented libs in the ebuild.  I tested and none appear to work, I think I got most of them right... feel free to double check.

### CODE REVIEW

**Comment by jorgicio** [comment]
With this PR is enough for now. Thanks.
Also, the app works, but it can't show when logged in (tried in MATE). But at least I can upload songs.

**Comment by kwhat** [comment]
You are too quick, I think the patch isnt needed.

**Comment by jorgicio** [comment]
May be useful though. Also, be careful when doing a `doexe` line and separate the files with the backslash, it gave me an error. Now it's fixed.

**Comment by kwhat** [comment]
Patch can be totally removed, files dir and all of src_prepare, IDK what it wasnt working the first time... clearly it is beer:30.

**Pull request merged**
